using Knip.Core.Configuration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Knip.Core.Analysis;

/// <summary>
/// BUILT-IN detection of source-/tool-generated syntax trees (H11). A generated tree is still WALKED
/// (its outbound edges/roots keep user symbols alive — extending the G8 compiler-generated-symbol rule
/// from symbols to whole files), but declarations inside it are marked "never report": the user did not
/// write that code and cannot delete it.
///
/// Detection is deliberately INDEPENDENT of <c>ignore.files</c>: user-configured ignores keep their
/// wholesale-drop semantics (invariant I1), while these built-in signals switch a tree to walk-don't-
/// report. The signals are the standard ones every generated-code convention uses:
///   1. a generator-produced in-memory tree (no backing file path);
///   2. a well-known generated file-name pattern (<c>*.g.cs</c>, <c>*.Designer.cs</c>, <c>*.generated.cs</c>, …);
///   3. the <c>// &lt;auto-generated/&gt;</c> file-header convention in the root's leading trivia;
///   4. a top-level declaration carrying <c>[GeneratedCode]</c>.
/// Only the common BCL / Roslyn surface is used, so Knip.Core stays net10.0/net472-agnostic (invariant #9).
/// </summary>
internal static class GeneratedCode
{
    // Well-known generated file-name globs. Kept SEPARATE from IgnoreConfig.Files on purpose: this is
    // the built-in generated-detection surface (walk-don't-report), not the user ignore list (drop).
    private static readonly string[] PathGlobs =
    [
        "**/*.g.cs", "**/*.g.i.cs", "**/*.Designer.cs", "**/*.generated.cs",
        "**/GlobalUsings.g.cs", "**/*.AssemblyInfo.cs", "**/*.AssemblyAttributes.cs",
    ];

    public static bool IsGenerated(SyntaxTree tree, SyntaxNode root)
    {
        var path = tree.FilePath;

        // (1) Generator-produced tree: source generators add trees to the Compilation with no backing
        // file on disk (empty FilePath). These are always "generated" by definition.
        if (string.IsNullOrEmpty(path)) return true;

        // (2) Well-known generated file-name patterns.
        if (Glob.IsMatchAny(path, PathGlobs)) return true;

        // (3) The `// <auto-generated>` header convention: a comment in the root's leading trivia whose
        // text contains "<auto-generated". This is the header Roslyn itself uses (IsGeneratedCode) and
        // the one EF/T4/designers emit.
        if (HasAutoGeneratedHeader(root)) return true;

        // (4) A top-level type carrying [GeneratedCode] (e.g. EF migrations, many generators).
        return HasGeneratedCodeAttribute(root);
    }

    private static bool HasAutoGeneratedHeader(SyntaxNode root)
    {
        // Only the FIRST leading trivia block (the file header) counts — an "<auto-generated>" mention
        // buried deep in the file must not flip a hand-written tree. Restrict to trivia at the very top.
        var leading = root.GetLeadingTrivia();
        foreach (var trivia in leading)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                && !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                continue;
            var text = trivia.ToString();
            if (text.Contains("<auto-generated", StringComparison.Ordinal)) return true;
        }
        return false;
    }

    private static bool HasGeneratedCodeAttribute(SyntaxNode root)
    {
        foreach (var node in root.ChildNodes())
        {
            if (node is BaseNamespaceDeclarationSyntax ns)
            {
                foreach (var member in ns.Members)
                    if (member is MemberDeclarationSyntax m && HasGeneratedCodeAttribute(m)) return true;
            }
            else if (node is MemberDeclarationSyntax member && HasGeneratedCodeAttribute(member))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasGeneratedCodeAttribute(MemberDeclarationSyntax member)
    {
        foreach (var list in member.AttributeLists)
            foreach (var attr in list.Attributes)
            {
                var name = attr.Name switch
                {
                    QualifiedNameSyntax q => q.Right.Identifier.Text,
                    IdentifierNameSyntax i => i.Identifier.Text,
                    _ => attr.Name.ToString(),
                };
                if (name is "GeneratedCode" or "GeneratedCodeAttribute") return true;
            }
        return false;
    }
}
