<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>CS0067;CS0169;CS0649;IDE0051;IDE0052</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B1B2.Lib\CatB.B1B2.Lib.csproj" />
  </ItemGroup>

</Project>
