<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>CS0169;CS0649;IDE0051;IDE0052</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PluginOrigin.Lib\PluginOrigin.Lib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
