// <auto-generated/>
using System;

namespace CatH.H11;

// SOURCE-GENERATED code: matched by the built-in generated pattern "*.g.cs" AND carries the
// "// <auto-generated/>" header. It is WALKED (its edges keep user symbols alive) but its own
// declarations are NEVER reported (H11).
public sealed partial class Handler
{
    // (a) The generator's implementation of the user's partial Wire() hook. ConfigureServices() (a
    // root) calls Wire(), so this body is REACHABLE, and the edge it records — Wire() -> Invoke() —
    // keeps the user method Invoke() ALIVE now that generated trees are walked.
    partial void Wire()
    {
        Invoke();
    }
}

// (b) A dead symbol DECLARED inside the generated file: referenced from nowhere, so it is unreachable
// — yet it MUST NEVER be reported, because the user did not author it and cannot delete it.
internal static class GeneratedWiring
{
    public static void RegisterDead() { }
}
